Cloud Centre Portal/webapp/Models/ViewModels/HostedOrganisationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CloudCentre.Models.ViewModels
{
    public class HostedOrganisationViewModel
    {
        public int ID { get; set; }
        public int PartnerID { get; set; }
        public string Name { get; set; }
        public string OU { get; set; }
        public int StatusID { get; set; }
        public bool? DynamicsEnabled { get; set; }

        public string PartnerName { get; set; }
        public string StatusName { get; set; }

        public virtual ICollection<DomainNameViewModel> DomainNames { get; set; }
        public virtual ICollection<PhoneNumbersViewModel> PhoneNumbers { get; set; }
    }
}

Cloud Centre Portal/webapp/Controllers/HostedOrganisationController.cs
using AutoMapper;
using CloudCentre.Attributes;
using CloudCentre.Models;
using CloudCentre.Models.ViewModels;
using CloudCentre.Services;
using CloudCentre.Services.Abstract;
using CloudCentrePortal.DAL.Model;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CloudCentre.Controllers
{
    [HostedOrganisation]
    public class HostedOrganisationController : Controller
    {
        private readonly IHostedOrganisationService _hostedOrganisationService;
        private readonly IUserManagerService _userService;

        public HostedOrganisationController(IHostedOrganisationService hostedOrganisationService, IUserManagerService userService)
        {
            this._hostedOrganisationService = hostedOrganisationService;
            this._userService = userService;
        }

        public ActionResult Index()
        {

            string userId = User.Identity.GetUserId();
            string role = _userService.GetUserRole(userId).FirstOrDefault();

            List<HostedOrganisationViewModel> viewModelList = Mapper.Map<List<HostedOrganisationViewModel>>(_hostedOrganisationService.GetHostedOrganisations(userId, role));
            return View(viewModelList);
        }

        public ActionResult AddDomainName()
        {
            var domainNameViewModelViewModel = new DomainNameViewModel();
            return PartialView("_DomainNamesPartial", domainNameViewModelViewModel);
        }

        public ActionResult AddPhoneNumber()
        {
            var phoneNumbersViewModel = new PhoneNumbersViewModel();
            return PartialView("_PhoneNumberPartial", phoneNumbersViewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new HostedOrganisationViewModel());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HostedOrganisationViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }


            HostedOrganisation hostedOrganisation = Mapper.Map<HostedOrganisation>(viewModel);
            ServiceResult result = _hostedOrganisationService.AddHostedOrganisation(hostedOrganisation);

            if (!result.IsValid)
            {
                result.Errors.ToList().ForEach(x => ModelState.AddModelError(x.Key.ToString(), x.Value));
                return View();
            }

            TempData["message"] = "Hosted Organisation has been added";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? Id)
        {
            if (Id == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            int intId = Convert.ToInt32(Id);
            if (intId == 0 || intId < 0) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }

            HostedOrganisation hostedOrganisation = _hostedOrganisationService.GetHostedOrganisation(intId);
            if (hostedOrganisation == null)
            {
                TempData["Error"] = "Error when editing Hosted Organisation";
                return RedirectToAction("Index");
            }

            HostedOrganisationViewModel hostedOrganisationViewModel = Mapper.Map<HostedOrganisationViewModel>(hostedOrganisation);
            return View(hostedOrganisationViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HostedOrganisationViewModel viewModel)
        {
            if (viewModel == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            if (!ModelState.IsValid) { return View(viewModel); }
            HostedOrganisation hostedOrganisation = _hostedOrganisationService.GetHostedOrganisation(viewModel.ID);
            hostedOrganisation.DomainNames.ToList().ForEach(x => { hostedOrganisation.DomainNames.Remove(x); _hostedOrganisationService.RemoveDomainNames(x); });
            hostedOrganisation.PhoneNumbers.ToList().ForEach(x => { hostedOrganisation.PhoneNumbers.Remove(x); _hostedOrganisationService.RemoveTelephone(x);});

            Mapper.Map(viewModel, hostedOrganisation);

            ServiceResult result = _hostedOrganisationService.UpdateHostedOrganisation(hostedOrganisation);
            if (!result.IsValid)
            {
                result.Errors.ToList().ForEach(x => ModelState.AddModelError(x.Key.ToString(), x.Value));
                return View();
            }

            TempData["message"] = "Hosted Organisation has been edited";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult ConfirmDelete(int Id)
        {
            if (Id == 0 || Id < 0) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            HostedOrganisation hostedOrganisation = _hostedOrganisationService.GetHostedOrganisation(Id);
            if (hostedOrganisation == null)
            {
                TempData["Error"] = "Error when deleting Hosted Organisation";
                return RedirectToAction("Index");
            }

            HostedOrganisationViewModel hostedOrganisationViewModel = Mapper.Map<HostedOrganisationViewModel>(hostedOrganisation);
            return View(hostedOrganisationViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int Id)
        {
            if (Id == 0 || Id < 0) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            HostedOrganisation hostedOrganisation = _hostedOrganisationService.GetHostedOrganisation(Id);
            hostedOrganisation.StatusID = (int)StatusEnum.Disabled;
            ServiceResult result = _hostedOrganisationService.UpdateHostedOrganisation(hostedOrganisation);

            if (!result.IsValid)
            {
                result.Errors.ToList().ForEach(x => TempData["Error"] = x.Value);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Hosted Organisation has been deleted";
            return RedirectToAction("Index");
        }


    }
}

Cloud Centre Portal/webapp/Views/HostedOrganisation/ConfirmDelete.cshtml
@model CloudCentre.Models.ViewModels.HostedOrganisationViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm("Delete", "HostedOrganisation", FormMethod.Post)) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)
        <div class="">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

Cloud Centre Portal/webapp/Views/HostedOrganisation/Create.cshtml
@model CloudCentre.Models.ViewModels.HostedOrganisationViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationBootstrap()

    <div class="form-horizontal col-md-12">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PartnerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.PartnerID, (IEnumerable<SelectListItem>)ViewBag.AllPartners, "--Select Partner--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PartnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.OU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.StatusID, (IEnumerable<SelectListItem>)ViewBag.AllStatuses, "--Select Status--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DynamicsEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.DynamicsEnabled, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DynamicsEnabled, "", new { @class = "text-danger" })

               

            </div>
        </div>

        <p class="text-left"><input type="button" class="btn btn-default" id="addDomainName" name="addDomainName" value="Add Domain Name"></p>
        <div id="next-DomainName" class="col-md-12 pull-right">
        </div>


        <p class="text-left"><input type="button" class="btn btn-default" id="addPhoneNumber" name="addPhoneNumber" value="Add Phone Number"></p>
        <div id="next-PhoneNumber" class="col-md-12 pull-right">
        </div>


        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

Cloud Centre Portal/webapp/Views/HostedOrganisation/Edit.cshtml
@model CloudCentre.Models.ViewModels.HostedOrganisationViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <p class="text-left"><input type="button" class="btn btn-default" id="addDomainName" name="addDomainName" value="Add Domain Name"></p>
        <p class="text-left"><input type="button" class="btn btn-default" id="addPhoneNumber" name="addPhoneNumber" value="Add Phone Number"></p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PartnerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PartnerID, (IEnumerable<SelectListItem>)ViewBag.AllPartners, "--Select Partner--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PartnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StatusID, (IEnumerable<SelectListItem>)ViewBag.AllStatuses, "--Select Status--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DynamicsEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DynamicsEnabled, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DynamicsEnabled, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="container col-md-12">
            @if (Model.DomainNames.ToList().Count() == 0)
            {
                <div id="next-DomainName" class="col-md-4">
                </div>

            }

            @foreach (var item in Model.DomainNames)
            {
                <div id="next-DomainName" class="col-md-12">
                    @{Html.RenderPartial("_DomainNamesPartial", item);}
                </div>
            }

        </div>


        <div class="container col-md-12">
            @if (Model.PhoneNumbers.ToList().Count() == 0)
            {
                <div id="next-PhoneNumber" class="col-md-4">
                </div>

            }

            @foreach (var item in Model.PhoneNumbers)
            {
                <div id="next-PhoneNumber" class="col-md-12">
                    @{Html.RenderPartial("_PhoneNumberPartial", item);}
                </div>
                        }

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

Cloud Centre Portal/webapp/Views/HostedOrganisation/Index.cshtml
@model IEnumerable<CloudCentre.Models.ViewModels.HostedOrganisationViewModel>

@Html.Partial("_ShowMessage")

<h2>Hosted Organisations</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-default" })
</p>

<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OU)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DynamicsEnabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PartnerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OU)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.DynamicsEnabled)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PartnerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { Id = item.ID }, new { @class = "btn btn-default" })
            @Html.ActionLink("Delete", "ConfirmDelete", new { Id = item.ID }, new { @class = "btn btn-default" })
            @Html.ActionLink("Add User", "Register", "Account", new { Id = item.ID }, new { @class = "btn btn-default" })
        </td>
    </tr>
}

</table>

Cloud Centre Portal/webapp/Views/HostedOrganisation/_DomainNamesPartial.cshtml
@model CloudCentre.Models.ViewModels.DomainNameViewModel


<div class="DomainNameRow col-md-5 pull-left text-center">
    @using (Html.BeginCollectionItem("DomainNames"))
    {
        <h2>Domain Name</h2>
        <div class="form col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.DomainName, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.DomainName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DomainName, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StatusName, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownListFor(model => model.StatusID, (IEnumerable<SelectListItem>)ViewBag.AllStatuses, "--Select Status--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ExchangeEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.ExchangeEnabled, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExchangeEnabled, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SFBEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.SFBEnabled, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SFBEnabled, "", new { @class = "text-danger" })
            </div>

            <a href="#" class="deleteDomainRow btn btn-default text-center">Delete Item</a>
        </div>
    }
</div>